### ISSUE TITLE
Should `PALOMA_KEY` be private?

### ISSUE THREAD

**Issue by pegahcarter** [VolumeFi/twap_bot_python_script#28]
https://github.com/VolumeFi/twap_bot_python_script/blob/ccdced65c3d8e6f70051f9abcba805d1f9e03d1a/run.sh#L2

**Comment by taariq** [comment]
Thank you @pegahcarter. You are correct. Let me check.

**Comment by taariq** [comment]
FIxed with https://github.com/VolumeFi/twap_bot_python_script/pull/29
